# List of input/precision parameters actually read
# (all other parameters set to default values)
# Obtained with CLASS v2.6.3 (for developers: svn version 6142M)
#
# This file can be used as the input file of another run
#
h = 0.67
T_cmb = 2.7255
Omega_b = 0.049
N_eff = 1.01533
Omega_cdm = 0.268580851704
N_ncdm = 2
ncdm_psd_parameters = 0.3 ,0.5, 0.05
m_ncdm = 0.00868907, 0.05
T_ncdm = 0.7164863646133482, 0.7164863646133482
deg_ncdm = 1, 1
Omega_k = 0.0
Omega_fld = 0.
YHe = 0.25
recombination = RECFAST
reio_parametrization = reio_camb
z_reio = 10.
reionization_exponent = 1.5
reionization_width = 1.5
helium_fullreio_redshift = 3.5
helium_fullreio_width = 0.5
annihilation = 0.
decay = 0.
output = mPk
non linear = PT
PNG = NO
IR resummation = NO
Bias tracers = NO
RSD = NO
Omfid = 0.31
modes = s
lensing = no
ic = ad
P_k_ini type = analytic_Pk
k_pivot = 0.05
A_s = 2.215e-9
n_s = 0.9619
alpha_s = 0.
P_k_max_h/Mpc = 100.
z_pk = 0.0, 0.25, 0.5, 1.0
z_max_pk = 10.
root = output/myfid_
write background = no
write parameters = yeap
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
spectra_verbose = 1
nonlinear_verbose = 1
nonlinear_pt_verbose = 1
lensing_verbose = 1
output_verbose = 1
#
